### PR TITLE
Added Depth Map to Realsense Camera

### PR DESCRIPTION
**Pull request by bitscuity**
The `realsense.py` file now contains methods to get the depth image and depth map of the device using the `pyrealsense2` wrapper calls.

### CODE REVIEW

**Comment by Victorlouisdg** [comment]
A few things we need to address:

**Depth-color field of view differences** 
Some Realsense cameras have a [bigger depth FoV than color FoV](https://www.intelrealsense.com/depth-camera-d435/). Luckily it seems to be pretty easy to align depth and color in that case (see [align-depth2color.py](https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/align-depth2color.py)). I think we should do that because it's what most users will want. After aligning the depth with color images, the intrinsics also become the same, so then we could remove `self._depth_intrinsics_matrix`.

**Depth map and image datatypes**
The realsense SDK seems to return depth values as `rs.format.z16` which become `np.uint16` through `np.asanyarray()`. This is also what the methods in the current PR seem to return. However in camera interface we promise/expect 32-bit floats from `get_depth_map()` and `uint8` from `get_depth_image()`, so this PR should be made consistent with that. We should also try to do the distance -> grayscale conversion ("normalization") [similar to the ZED SDK](https://www.stereolabs.com/docs/depth-sensing/using-depth/#displaying-depth-image) for the depth image.

**Testing**
We should add the tests from `test_hw.py` to this file. However we can't use `manual_test_stereo_rgbd_camera()` because we the realsenses only have a single color camera.

Additionally, maybe we should add datatype checks to the `manual_test` functions?

**Comment by Victorlouisdg** [comment]
For reference, this is what the depth images from the ZED look like:
image

**Comment by bitscuity** [comment]
there you go, the remarks have been addressed now :)

**Comment by Victorlouisdg** [comment]
The current depth images maps have large black regions (missing values), do we want to fill these in/do some smoothing like ZED? Does the realsense SDK have this functionality?
image

**Comment by Victorlouisdg** [comment]
This is a screenshot from the Realsense viewer with hole filling enabled. I'm not sure if I like it, but it's closer to the default for the ZEDs.
image

**Comment by Victorlouisdg** [comment]
I cleaned up some code and enabled several filters for the depth images/maps. Below is an example of what they look like right now. For me this PR is ready to merge.
image

**Pull request merged**
